apiVersion: batch/v1
kind: Job
metadata:
  name: midbrain-rtsort
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
      - name: rtsort
        image: aidanmorson/rt-sort:v1
        imagePullPolicy: Always
        resources:

          # GPU Run
          requests:
            cpu: "10"
            memory: "45Gi"
            ephemeral-storage: "250Gi"
            nvidia.com/gpu: "1"
          limits:
            cpu: "10"
            memory: "45Gi"
            ephemeral-storage: "250Gi"
            nvidia.com/gpu: "1"

        command: ["conda", "run", "--no-capture-output", "-n", "rt-sort-minimal", "/usr/bin/time", "-v", "python", "sorter.py"]
        args:
          - s3://braingeneers/ephys/2024-10-31-e-SmitsMidbrain/original/data/24481_SmitsMO_D49_sect300_20241031.raw.h5
          - s3://braingeneers/ephys/2024-10-31-e-SmitsMidbrain/original/shared/

        env:
          - name: "PYTHONUNBUFFERED"
            value: "true"
          - name: "PYTHONPATH"
            value: "/app"
          # Ceph (internal)
          - name: "ENDPOINT_URL"
            value: "https://s3.braingeneers.gi.ucsc.edu"  # ceph internal
          - name: "S3_ENDPOINT"
            value: "s3.braingeneers.gi.ucsc.edu" # ceph internal

        volumeMounts:

          # Ceph credentials
          - name: "prp-s3-credentials"
            mountPath: "/root/.aws/credentials"
            subPath: "credentials"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - gpu-10.nrp.mghpcc.org
                - gpu-11.nrp.mghpcc.org
                - gpu-12.nrp.mghpcc.org
                - gpu-13.nrp.mghpcc.org
                - gpu-14.nrp.mghpcc.org
                - gpu-15.nrp.mghpcc.org
                - gpu-16.nrp.mghpcc.org
                - gpu-17.nrp.mghpcc.org
                - gpu-18.nrp.mghpcc.org
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "PreferNoSchedule"
          
      restartPolicy: Never
      volumes:
        # Secrets file for nautilus s3 credentials .aws/credentials and .s3cfg
        - name: prp-s3-credentials
          secret:
            secretName: prp-s3-credentials
        - name: ephemeral
          emptyDir: {}